app/urls.py
from django.urls import path
from .import views

app_name = 'app'

urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('Search/', views.sm_search, name='sm_search'),
    path('search/', views.search_list, name='search_list'),
    path('newsletter/', views.newsletter, name='newsletter'),
    path('<slug:category_slug>/', views.product_list, name='product_list_category'),
    path('<int:id>/<slug:slug>/', views.product_details, name='product_details'),
  ]

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns =[
    path('', views.cart_detail, name='cart_detail'), 
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
  ]

coupon/urls.py
from django.urls import path
from . import views

app_name = 'coupon'

urlpatterns = [
    path('apply/', views.coupon_apply, name='coupon_apply'),
  ]

shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('jet/', include('jet.urls', 'jet')),  
    path('jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')), 
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('accounts/', include('account.urls')),
    path('coupon/', include('coupon.urls', namespace='coupon')),
    path('', include('app.urls', namespace='app')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]

class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    override = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST
from django.contrib import messages
from app.models import Product
from .cart import Cart
from .forms import CartAddProductForm
from django.http import JsonResponse
from coupon.forms import CouponForm

# Create your views here.

#@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    add_form = CartAddProductForm(request.POST)
    if add_form.is_valid():
        cd = add_form.cleaned_data
        cart.add(product=product, quantity=cd['quantity'], override_quantity=cd['override'])
        messages.success(request, '✓ Product added Successfully')
    return redirect('cart:cart_detail')
    
#@require_POST
def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id= product_id)
    cart.remove(product=product)
    messages.success(request, '✓ Product removed from Cart')
    return redirect('cart:cart_detail')
    
def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'], 'override': True})
    coupon_form = CouponForm()
    return render(request, 'cart/detail.html', {'cart': cart, 'coupon_form': coupon_form})
  

cart/templates/cart/detail.html
{% extends 'base.html' %}
{% load static bootstrap_icons %}
{% block title %}Cart{% endblock %}
{% block content %}
{% if cart %}
  <div class="total_sm mt-1">
    <p style="color:#666; font-size:14px; height:10px;" class="px-2">SUMMARY</p>
    {% if cart.coupon %}
    <table class="bg-white w-100" border="0">
      <tr>
        <td class="px-2">Subtotal</td>
        <td colspan="4"></td>
        <td>${{ cart.get_total_price }}</td>
      </tr>
      <tr>
        <td class="px-2">"{{ cart.coupon.code }}" coupon({{ cart.coupon.discount }}% off)</td>
        <td colspan="4"></td>
        <td class="text-danger">-${{ cart.get_discount|floatformat:2 }}</td>
      </tr>
      <tr>
        <td class="fw-bold fs-5 px-2">Total Price</td>
        <td colspan="4"></td>
        <td class="fw-bold fs-5 px-2">${{ cart.get_total_price_after_discount|floatformat:2 }}</td>
      </tr>
    </table>
    {% else %}
    <div style="background:white; font-size:20px;" class="px-3 py-2 fw-bold">
      Total Price <span class="float-end">${{ cart.get_total_price }}</span>
    </div>
    {% endif %}
  </div>
  <div class="cart_list">
    <p style="color:#666; font-size:14px; height:15px;" class="px-2 pt-2 pb-3">CART({{ cart|length }})</p>
    {% for item in cart %}
      {% with product=item.product %}
      <div class="mx-1 p-1 p-md-2 mb-4" style="background:#fff; border-radius:9px;">
        <div class="row">
          <div class="col-4">  
              <a href="{{ product.get_absolute_url }}">
                <img class="cart_img me-3 ms-2 my-2" src="{% if product.image %}{{ product.image.url }}{% else %}{% static 'img/no_image.png' %}{% endif %}" alt="image" />
              </a>
          </div>
          <div class="col-7 ms-2">
              <a href="{{ product.get_absolute_url }}">
                <span style="font-size:14px;" class="d-inline-block pt-3">{{ product.name }}</span>
              </a>
              <p style="font-size:20px;"class="d-block text-md-end fw-bold pb-1 py-2 ">${{ item.price }}</p>
              <form action="{% url 'cart:cart_add' product.id %}" method="POST" class="pt-1 text-end pb-1 pt-2 px-1">
                 {% csrf_token %}
                  {{ item.update_quantity_form.quantity }}
                 {{ item.update_quantity_form.override }}
                <button style="background:#ff933b; font-size:10px; border-radius:7px;" class=" border-0 text-center py-1 px-1 text-white" type="submit">update</button>
               </form>
           </div>
               <div style="align-items:start;"><form action="{% url 'cart:cart_remove' product.id %}" method="POST">
                {% csrf_token %}
                  <button style="background:#fff; color:#ff933b; font-size:16px;" class=" border-0 text-start fw-bold px-2 mb-2 mt-2 pb-2 "> <span>{% bs_icon 'trash' size="1em" %}</span>REMOVE</button>
                 </form></div>
          </div>
        </div>
      {% endwith %}
    {% endfor %}
 </div>
  <div class="d-md-none ">
    <div><form action="{% url 'coupon:coupon_apply' %}"  class="couponForm ms-1 py-4 px-2"  method="POST">
      {% csrf_token %}
      {{ coupon_form }}
      <button style="background:#ff933b" class="text-white border-0 p-1 w-25" type="submit">Apply</button>
    </form></div>
    <a class="text-decoration-none"href="{% url 'order_payout' %}"><button style="background:#ff933b; font-size:17px; color:#fff; border-radius:7px;" class="w-100 border-0 py-2 px-3 fw-bold my-4" type="submit">CHECKOUT {% if cart.coupon %}(${{ cart.get_total_price_after_discount|floatformat:2 }}){% else %}(${{ cart.get_total_price|floatformat:2 }}){% endif %}</button></a>
  </div>
  <div class="total mt-1">
    <p style="background:#fff; color:#333; font-size:14px;" class="ps-2 py-2 mb-1">CART SUMMARY</p>
    <div style="background:white;">
    {% if cart.coupon %}
    <table class="w-100" border="0">
      <tr>
        <td class="px-2">Subtotal</td>
        <td colspan="4"></td>
        <td>${{ cart.get_total_price }}</td>
      </tr>
      <tr>
        <td class="px-2">"{{ cart.coupon.code }}" coupon({{ cart.coupon.discount }}% off)</td>
        <td colspan="4"></td>
        <td class="text-danger">-${{ cart.get_discount|floatformat:2 }}</td>
      </tr>
      <tr>
        <td class="fw-bold fs-5 px-2">Total Price</td>
        <td colspan="4"></td>
        <td class="fw-bold fs-5 px-2">${{ cart.get_total_price_after_discount|floatformat:2 }}</td>
      </tr>
    </table>
    {% else %}
      <div style="font-size:20px;" class="px-3 py-2 fw-bold">Total Price<span class="float-end">${{ cart.get_total_price|floatformat:2 }}</span></div>
    {% endif %}
       <form action="{% url 'coupon:coupon_apply' %}" class="couponForm my-4 ms-1" method="POST">
          {% csrf_token %}
            {{ coupon_form }}
          <button style="background:#ff933b" class="text-white border-0 p-1 w-25" type="submit">Apply</button>
        </form>
      <div class="mx-3">
        <a class="text-decoration-none" href="{% url 'order_payout' %}"><button style="background:#ff933b; font-size:17px; color:#fff; border-radius:7px;" class="w-100 border-0 py-2 px-3 fw-bold mt-5 mb-3" type="submit">CHECKOUT {% if cart.coupon %}(${{ cart.get_total_price_after_discount |floatformat:2 }}){% else %}(${{ cart.get_total_price|floatformat:2 }}){% endif %}</button></a>
      </div>
    </div>
  </div>
  {% else %}
  <img class="empty_img mb-2 mx-auto d-block" src="{% static 'img/empty_cart.png' %}" alt="" />
  <p style="font-size:18px;" class="fw-bold text-center">Your cart is empty!</p>
    <p class=" text-center">Click button below to start shopping</p>
    <div class="text-center"><a class="text-decoration-none" href="{% url 'app:product_list' %}">
      <button class="button p-2 mx-auto text-center border-0 d-block fw-bold" type="submit">
        START SHOPPING
      </button></a>
    </div>
  {% endif %}
{% endblock %}