app/urls.py
from django.urls import path
from .import views

app_name = 'app'

urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('Search/', views.sm_search, name='sm_search'),
    path('search/', views.search_list, name='search_list'),
    path('newsletter/', views.newsletter, name='newsletter'),
    path('<slug:category_slug>/', views.product_list, name='product_list_category'),
    path('<int:id>/<slug:slug>/', views.product_details, name='product_details'),
  ]

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns =[
    path('', views.cart_detail, name='cart_detail'), 
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
  ]

shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('jet/', include('jet.urls', 'jet')),  
    path('jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')), 
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('accounts/', include('account.urls')),
    path('coupon/', include('coupon.urls', namespace='coupon')),
    path('', include('app.urls', namespace='app')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/templates/base.html
{% load static bootstrap_icons %}
<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <title>{% block title %}{% endblock %}</title>
    <style type="text/css">
      *{
        box-sizing: border-box;
      }
      body{
        margin: 0;
        padding: 0;
        font-family: 'Poppins', sans-serif;
        background: #efefef;
      }
      a{
        color: black;
        text-decoration: none;
      }
      .menu{
        padding: 5px 15px 5px;
      }
      .menu2{
        padding: 5px 15px 5px;
      }      
      .span input, .span button{
        border-radius: 7px;
      }
      .dd-btn{
        border: none;
      }
      .dd-content{
        transition: height .5s;
        box-shadow: 0 14px 20px rgba(0,0,0,0.30), 0 14px 11px rgba(0,0,0,0.22);
        height: 0px;
        width: 100%;
        background: white;
      }
      .dd:hover > .dd-content {
         height: 120px;
      }
      .cont{
        display: grid;
        justify-content: center;
        grid-template:auto auto/20% 70%;
        gap: 30px;
      }
      .sidebar ul{
        list-style-type: none;
      }
      .sidebar ul li.selected{
        background: #ff933b;
        border-radius: 4px;
      }
      .sidebar ul li.selected a{
        color: white;
      }
      .eshop img{
        width: 100%;
        height: auto;
      }
      .main{
        float: left;
        width: 100%;
        overflow: hidden;
      }
      .main .item{
        width: 23%;
      }
      .cart_img{
          width:100%
      }
      .empty_img{
        width: 30%;
      }
      .cart_list{
        float:left;
        width: 60%;
      }
      .total{
        float: left;
        width: 36%;
        margin-left: 20px;
      }
     
      ul.messages {
           margin:10px 6px;
           padding:0;
           list-style-type:none;
          }
        ul.messages li.success,
        ul.messages li.warning,
        ul.messages li.error,
        ul.messages li.info {
            margin:0;
            padding:14px 20px;
            list-style:none;
            color:#fff;
          }

        ul.messages li.success { background:#b4ffb4; }
        ul.messages li.success a { color:#67ff92; }
        
        ul.messages li.error { background:#ff9595; color:#fe6777; }
        ul.messages li.error a { color:#fe6777; }

        ul.messages li.info { background:#f4ff44; color:#cacdac; }
        ul.messages li.info a { color:#cacdac; }

        ul.messages li.warning { background:#d8a33a; }
        ul.messages li.warning a { color:#fadaac; }
        ul.messages li a.close {
            margin:0;
            float:right;
            opacity:1;
            font-size: 19px;
            border:none;
            text-decoration: none;
          }
          .button{
            color: white;
            background: #ff933b;
            width: 95%;
            border-radius: 7px;
          }
          .clearfix::after{
          content:"";
          clear:both;
          display:table;
          }
          .search_item {
            float: left;
            width: 45%;
          }
          .couponForm input{
          width: 70%;
          padding: 5px;
          border: none;
          background: #ccc;
        }
        footer{
          background: #777;
          padding-bottom: 30px;
        }
      @media only screen and (min-width:768px){
        .menu{
          display: none;
        }
        .menu1{
          padding: 10px 10px 5px 15px;
        }
        .menu2{
          padding: 10px 10px 5px 15px;
        }
        #searched{
          display: none;
        }
        .total_sm{
          display: none;
        }
        ul.messages {
           margin:10px 25%;
        }
        ul.messages li.success,
        ul.messages li.warning,
        ul.messages li.error,
        ul.messages li.info {
            margin:0;
            padding:14px 20px;
            list-style:none;
            color:#fff;
          }
          .button{
            width: 30%;
            margin-left, margin-right:auto ;
          }
          .form{
            margin: 0 30%;
          }
          th, td{
            padding-right: 15px;
          }
      }
      @media only screen and (max-width:767px){
        .menu span, .span, .menu2 span {
          display: none;
        }
        .menu1{
          display: none;
        }
        .cont{
        grid-template:auto auto/100%;
        }
        .sidebar{
          display: none;
        }
        .main .item{
          width: 45%;
        }
        .cart_list{
          width: 100%;
        }
        .total{
          display: none;
        }
        td > h4, th > h4{
          font-size: 16px;
        }
        td > h5{
          font-size: 15px;
        }
      }
    </style>
  </head>
  <body>
    <div style="background:white; width:100%;" class="position-fixed py-3 px-4 d-inline-block">
      <a class="text-decoration-none text-dark fs-1 fw-bolder" href="{% url 'app:product_list' %}">Eshop</a>
      <div class="d-inline-block px-2 pt-2 float-end">
        <form action="{% url 'app:search_list' %}" method="GET" class="d-inline">
          <a id="searched" class="text-decoration-none text-dark" href="{% url 'app:sm_search' %}"><span class="menu">{% bs_icon 'search' size='1.2em' %}</span></a><span class="span fw-bold"><input type="search" value="{{ search_post }}"  class="p-2 me-2" name="q" id="search" placeholder="Search products and categories"/><button style="background:#ff933b; border:none;" class="p-2" type="submit">{% bs_icon 'search' size='1.2em' color='white' %}</button></span>
         </form>
         {% if request.user.is_authenticated %}
         <a class="text-decoration-none text-dark" href="{% url 'user_profile' %}"><span class="menu">{% bs_icon 'person-check' size='1.4em' %}</span></a>{% else %}<a class="text-decoration-none text-dark" href="{% url 'login' %}"><span class="menu">{% bs_icon 'person' size='1.4em' %}</span></a>{% endif %}<span class="menu1">{% if request.user.is_authenticated %}{% bs_icon 'person-check' size='1.4em' %}<span class="dd position-relative d-inline-block"><button  class="dd-btn py-2 px-4 text-center btn btn-dark w-auto text-white">Hi, {{ request.user.first_name }}! {% bs_icon 'caret-down-fill' %}</button><div class="dd-content position-absolute  overflow-hidden">
              <a class="pt-2 px-2 pb-1 d-block " href="{% url 'user_profile' %}">{% bs_icon 'person' size='1.4em' %} My Account</a>
              <hr />
              <a style="color:#ff933b;" class="fw-bold d-block text-center" href="{% url 'Logout' %}">Logout</a>
            </div></span>{% else %}{% bs_icon 'person' size='1.4em' %}<span class="dd position-relative d-inline-block"><button class="dd-btn py-2 px-4 text-center btn btn-dark w-auto text-white">Account {% bs_icon 'caret-down-fill' %}</button>
              <div class="dd-content position-absolute  overflow-hidden">
                <a class="my-4 mx-2 fw-bold d-block text-center w-auto p-2" style="font-size:13px; background:#ff933b; color:#fff;" href="{% url 'login' %}">SIGN-IN</a>
              </div>
              </span>{% endif%}</span>
         <a class="text-decoration-none text-dark" href="{% url 'cart:cart_detail' %}"><span class="ps-4 menu2">{% bs_icon 'cart' size='1.4em' %}<p style="font-size:8px; margin-top:-10px; margin-left:-10px;" class="bg-dark rounded-circle text-white d-inline px-2 py-1">{{ cart|length }}</p><span class="ms-2 fw-bold">Cart</span></span></a>
      </div>
    </div>
    <div style="padding-top:100px;" class="container-fluid overflow-hidden">
      {% if messages %}
        <ul class="messages">
          {% for message in messages %}
            <li class="{{ message.tags }}"><strong>{{ message|safe }}</strong>
            <a href="#" class="close">x</a>
            </li>
          {% endfor %}
        </ul>
      {% endif %}
      {% block content %}
      {% endblock %}
    </div>
    <footer class="w-auto mt-5 overflow-hidden">
      <div class="row">
        <div class="px-3 col-md-8">
          <div class="p-3 text-white">
            <p class="fw-bold fs-5">Subscribe to our Newsletter</p>
            <form class="" action="{% url 'app:newsletter' %}" method="POST">
              {% csrf_token %}
              <span><input style="padding:10px;" type="email" class=" form-control d-inline w-50" id="email" placeholder="Enter email" name="email" required>
              <button style="background:#ff933b; color:white;" class="p-2 border-0" type="submit">Subscribe</button></span>
            </form>
          </div>
          <div class="p-3 text-white">
            <h4 class="text-decoration-underline">Contact Us</h4>
            <ul style="list-style-type:none" class="m-0 p-0">
              <li class="ps-2 py-2">Tel: <a class="text-white" href="tel: +2348118185345">+2348118185345</a></li>
              <li class="ps-2 py-2">Email: <a class="text-white" href="mailto: ferdinandchidera49@gmail.com">ferdinandchidera49@gmail.com</a></li>
              <li class="ps-2 py-2"><address>No.1 okochi road
                Unizik Junction,Awka</address></li>
            </ul>
          </div>
        </div>
        <div class="p-3 col-md-4">
          <div class="p-3 text-white">
            <h4 class="text-decoration-underline">Useful Links</h4>
            <ul style="list-style-type:none" class="m-0 p-0">
              <li class="ps-2 py-2"><a class="text-white" href="mailto:ferdinandchidera49?subject=Report a Product">Report a product</a></li>
              <li class="ps-2 py-2"><a class="text-white" href="mailto:ferdinandchidera49?subject=Become a seller">Become a seller</a></li>
            </ul>
          </div>
        </div>
      </div>
      <div class="my-3 text-center my-md-5">
        <a class="px-2 text-white" href="https://www.facebook.com/profile.php?id=100077376138673">{% bs_icon "facebook" size="1.5rem" %}</a>
        <a class="px-2 text-white" href="https://wa.link/ibcmpy">{% bs_icon "whatsapp" size="1.5rem" %}</a>
        <a class="px-2 text-white" href="https://www.linkedin.com/in/chidera-ferdinand-022503243">{% bs_icon "linkedin" size="1.5rem" %}</a>
        <a class="px-2 text-white" href="https://github.com/chidera-777/">{% bs_icon "github" size="1.5rem" %}</a>
      </div>
      <div class="text-white text-center">
        Copyright © Eshop 2022
      </div>
      <hr style="color:#000; border:1px solid black;" class="w-100"/>
      <div class="text-white text-center">
        Developed with {% bs_icon 'balloon-heart-fill' %} by FerdinandC
      </div>
    </footer>
  </body>
</html>

app/templates/newsletter.html
{% load static bootstrap_icons %}
<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <style type="text/css">
      body{
        background:#333;
        color: white;
      }
      .text-center{
        text-align: center;
      }
      .mb-0{
        margin-bottom: 0;
      }
      .my-3{
        margin-top: 1rem;
        margin-bottom: 1rem;
      }
      footer{
        margin-top: 25px;
        background: #666;
        padding: 8px;
      }
      .unsubscribe{
        text-decoration: underline;
        color: white;
      }
      img{
        max-width: 100%;
        height: auto;
      }
      .social{
        text-align: center;
        margin-top: 15px;
      }
      .social div{
        width: 20px;
        height: 20px;
        display: inline-block;
        margin-left: 5px;
        margin-right: 5px;
      }
      .social a img{
        border-radius: 50%;
      }
    </style>
  </head>
  <body>
    <div class="my-3">
      <img class="" src="https://images.pexels.com/photos/135620/pexels-photo-135620.jpeg?cs=srgb&dl=pexels-shattha-pilabut-135620.jpg&fm=jpg" alt="" />
    </div>
    <div class="text-center">
     <h3>Welcome to Eshop</h3> 
      <h3>Thanks for subscribing!</h3>
      <p style="font-size:11px" class="mb-2">To welcome you, we would like to give a 20% OFF on any item in Eshop</p>
      <p style="font-size:9px" class="mb-0">Coupon Code:</p>
      <p style="font-size:15px">SUMMER</p>
    </div>
    <footer class="mt-5">
      <div class="text-center">
        <p style="font-size:9px" >You're getting this email because you subscribed to our mailing list. If you'd like to stop getting the latest news about our offers, you can unsubscribe below</p>
        <div class="text-center my-1">
          <a style="font-size:10px" class="unsubscribe" href="#">unsubscribe</a>
        </div>
        <div class="social">
          <div>
              <a href="https://www.facebook.com/profile.php?id=100077376138673"><img src="https://www.edigitalagency.com.au/wp-content/uploads/Facebook-logo-blue-circle-large-transparent-png.png" alt="" /></a>            
          </div>
          <div>
              <a href="https://wa.link/ibcmpy"><img src="https://www.freepnglogos.com/uploads/whatsapp-png-logo-1.png" alt="" /></a>
          </div>
          <div>
              <a href="https://www.linkedin.com/in/chidera-ferdinand-022503243"><img src="https://www.freepnglogos.com/uploads/linkedin-in-logo-png-1.png" alt="" /></a>
          </div>
        </div>
      <p style="margin-top:5px; margin-bottom:10px;">Copyright © Eshop 2022</p>
      </div>
    </footer>
  </body>
</html>

app/templates/sm_search.html
{% load bootstrap_icons %}
<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <title></title>
  </head>
  <body>
    <div style="background:white; width:100%;box-shadow:2px 0px 3px #888;" class="position-fixed py-3 d-inline-block">
    <span><a href="/ " style="color:#000" class="text-decoration-none ps-1">{% bs_icon 'arrow-left' size='1.5rem' %}</a></span> 
      <form action="{% url 'app:search_list' %}" method="GET" class="d-inline">
        <span class="fw-bold"><input type="search" value="{{ search_post }}" style="border:1px solid transparent; border-right:1px solid #888"  class="w-75 p-1 me-2" name="q" id="search" placeholder="Search products and categories"/><button style="background:#fff; border:none;" class="p-1" type="submit">{% bs_icon 'search' size='1.2em' color='black' %}</button></span>
       </form>
     </div>
  </body>
</html>